#!/usr/bin/env bash
# =============================================================================
# Conan 2.x C/C++ package manager: pure Python, installed via pip --target.
# Requires our bundled Python to be built first.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMON_DIR="${SCRIPT_DIR}/.."

source "${COMMON_DIR}/tool-versions.sh"

log() { echo "===> $(date '+%H:%M:%S') $*"; }
err() { echo "ERROR: $*" >&2; }

TOOL_NAME="conan"
VERSION="${TOOL_CONAN_VERSION}"
PLATFORM="${PLATFORM:-linux-x86_64}"

TOOL_DIR="${TOOLS_CACHE_DIR}/built/${TOOL_NAME}"

# Require bundled Python
PY_BIN="${TOOLS_CACHE_DIR}/built/python/bin/python3"
if [[ ! -x "${PY_BIN}" ]]; then
    err "conan requires bundled Python at ${PY_BIN}; build python first"
    exit 1
fi

log "Installing Conan ${VERSION} (via pip --target ${TOOL_DIR})"

rm -rf "${TOOL_DIR}"
mkdir -p "${TOOL_DIR}"

# 1. pip install --target so package files end up in tools/conan/{conans,conan,...}
# rather than tools/python's site-packages.
"${PY_BIN}" -m pip install \
    --target="${TOOL_DIR}" \
    --no-warn-script-location \
    --upgrade \
    "conan==${VERSION}"

# 2. The conan executable itself is at tools/conan/bin/conan (a Python script)
# Wait — pip --target puts scripts in tools/conan/bin/conan, but on linux the
# entrypoint generated by pip uses the Python interpreter via shebang.
# Patch the shebang so the launcher uses our bundled python explicitly.
if [[ -f "${TOOL_DIR}/bin/conan" ]]; then
    # Replace shebang line with our bundled Python's absolute path
    # NOTE: this hardcodes a build-time path. Better: use a wrapper script.
    # We'll create a launcher .sh that invokes Python with PYTHONPATH set.
    rm -f "${TOOL_DIR}/bin/conan"
fi

# 3. Create a relocatable launcher
mkdir -p "${TOOL_DIR}/bin"
cat > "${TOOL_DIR}/bin/conan" << 'EOF'
#!/usr/bin/env bash
# Conan launcher: uses bundled Python and bundled Conan packages.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLCHAIN_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
CONAN_HOME="${SCRIPT_DIR}/.."
PYTHON_BIN="${TOOLCHAIN_ROOT}/tools/python/bin/python3"

if [[ ! -x "${PYTHON_BIN}" ]]; then
    echo "FATAL: bundled Python not found at ${PYTHON_BIN}" >&2
    exit 1
fi

export PYTHONPATH="${CONAN_HOME}:${PYTHONPATH:-}"
exec "${PYTHON_BIN}" -m conans.conan "$@"
EOF
chmod +x "${TOOL_DIR}/bin/conan"

# 4. Smoke test (using full PYTHONPATH)
PYTHONPATH="${TOOL_DIR}:${PYTHONPATH:-}" "${PY_BIN}" -m conans.conan --version | head -1

log "${TOOL_NAME} installed to ${TOOL_DIR}"
du -sh "${TOOL_DIR}"
